---
name: build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  std_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.9, 3.11, 3.12.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run black
        run: |
          black --check .

      - name: Run linter
        run: |
          pylama .

      - name: Run type checker
        run: |
          mypy -p napalm --config-file mypy.ini

      - name: Run Tests
        run: |
          py.test --cov=napalm --cov-report term-missing -vs --pylama

  build_docs:
    needs: std_tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r docs/requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Doctests
        run: |
          make doctest
